### ISSUE TITLE
Ostatni problem z case (chyba xD)

### ISSUE THREAD

**Issue by Ruske123** [SpaceMC-EU/SpaceMC-Bugi#10]
**Opisz bug**
Zła oprawa wizualna prawdopodobieństwa wypadnięcia przedmiotu ze skrzyni

**To Reproduce**
Dodać przedmiot

**Przewidywane zachowanie**
Zmienić oprawę wizualną na bardziej czytelną

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
System używa wag zauważyłem teraz tylko że Informacje nie wyświetlają poprawnego procenta gdy się zmienia liczby za pomocą główek System bazowany na bazie wag pozwala dać jakąkolwiek szanse na przedmiot się chce procentowy za bardzo nie ale myślałem na przemianie tylko nie wiem za bardzo jak to zaimplementować bo liczb po przecinku jest niesamowicie wiele....
