### ISSUE TITLE
Plots changeowner

### ISSUE THREAD

**Issue by Ruske123** [SpaceMC-EU/SpaceMC-Bugi#11]
**Opisz bug**
Nie można zmienić właściciela działki na osobę która jest offline

**To Reproduce**
Spróbować zmienić właściciela działki na osobę offline

**Przewidywane zachowanie**
Udana zmiana właściciela

**Screenshots**
Wysłałem ci na dsc

**Comment by PuccyDestroyerxXx** [comment]
Naprawione
