### ISSUE TITLE
Plots forceadd

### ISSUE THREAD

**Issue by Ruske123** [SpaceMC-EU/SpaceMC-Bugi#12]
**Opisz bug**
Tak samo jak z changeowner nie działa na osoby offline

**To Reproduce**
Spróbować dodać do działki osobę offline

**Przewidywane zachowanie**
Osoba offline powinna zostać dodana do działki

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Naprawione
