### ISSUE TITLE
Komenda /działka tele

### ISSUE THREAD

**Issue by Ruske123** [SpaceMC-EU/SpaceMC-Bugi#13]
**Opisz bug**
Po wpisaniu /działka tele wyskakuje komunikat o wystąpieniu błędu podczas próby tabowania komendy (mimo wszystko można ukończyć komendę ręcznie)

**To Reproduce**
Wpisać komendę

**Przewidywane zachowanie**
Nie wyskakiwanie błędu

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Nie mogę zreprodukować

**Comment by PuccyDestroyerxXx** [comment]
Działa poprawnie na razie
