### ISSUE TITLE
/działka nazwa

### ISSUE THREAD

**Issue by Ruske123** [SpaceMC-EU/SpaceMC-Bugi#14]
**Opisz bug**
Podczas próby zmiany nazwy wyskakuje komunikat że działka o takiej nazwie już istnieje i nazwa pozostaje niezmieniona

**To Reproduce**
Zmienić nazwę działki

**Przewidywane zachowanie**
Poprawna zmiana nazwy bez bulu oczu spowodowanego czerwonym komunikatem

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Mogłem zrobić zmiane bez problemu na nazwe która nie istnieje prosiłbym o reprodukcje przy mnie

**Comment by PuccyDestroyerxXx** [comment]
Działa poprawnie
