### ISSUE TITLE
kwadrat  śniegu która gryzie się z resztą otoczenia xD

### ISSUE THREAD

**Issue by akukwq** [SpaceMC-EU/SpaceMC-Bugi#15]
**Opisz bug**
Opisz dokładnie bug co się dzieje
W spawnie na kordynatach -381 57 -129 znajduje się kwadrat śniegu o wymiarach 2m * 2m i bardzo gryzie się z terenem 
**To Reproduce**
Jak go się reprodukuje czyli odtwarza / powtarza

**Przewidywane zachowanie**
Co powinno się stać według ciebie

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów
![image](https://user-images.githubusercontent.com/82155999/114268085-9591c280-99ff-11eb-97fc-376dd1d61252.png)

**Comment by PuccyDestroyerxXx** [comment]
Nie jest to jakiś poważny bug bardziej nie dopatrzenie ale racja
