### ISSUE TITLE
Nie ma portalu do endu

### ISSUE THREAD

**Issue by akukwq** [SpaceMC-EU/SpaceMC-Bugi#16]
**Opisz bug**
Opisz dokładnie bug co się dzieje
Na kordach do których przywiezie cię ender_eye nie ma portalu
**To Reproduce**
Jak go się reprodukuje czyli odtwarza / powtarza

**Przewidywane zachowanie**
Co powinno się stać według ciebie
powinien być portal
**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Bug już znany dawno zostanie naprawiony zamykam
