### ISSUE TITLE
możliwość zobaczenia (że dany administrator jest na serwerze) administatorów na vanishu

### ISSUE THREAD

**Issue by akukwq** [SpaceMC-EU/SpaceMC-Bugi#17]
**Opisz bug**
Opisz dokładnie bug co się dzieje
możliwość zobaczenia (że dany administrator jest na serwerze) administatorów na vanishu
**To Reproduce**
Jak go się reprodukuje czyli odtwarza / powtarza

wpisujesz komendę np. /ban i po tej komendzie możesz wybrać nick administratora którego nie ma nawet pod tab gdyż jest na vanishu
**Przewidywane zachowanie**
Co powinno się stać według ciebie
powinien się nie wyświetlać nick do wybrania administratora
**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Naprawione
