### ISSUE TITLE
/tpall

### ISSUE THREAD

**Issue by Cycu333** [SpaceMC-EU/SpaceMC-Bugi#18]
**Opisz bug**
Opisz dokładnie bug co się dzieje
Wpisuje /tpall i tpam wszystkich do siebie XDD po czym Nateś sie denerwuje i mnie wyzywa
**To Reproduce**
Jak go się reprodukuje czyli odtwarza / powtarza

**Przewidywane zachowanie**
Co powinno się stać według ciebie

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Naprawione XD
