### ISSUE TITLE
Obraz

### ISSUE THREAD

**Issue by Cycu333** [SpaceMC-EU/SpaceMC-Bugi#19]
**Opisz bug**
Mozna niszczyc obrazy na dzialkach <3
**To Reproduce**
Jak go się reprodukuje czyli odtwarza / powtarza

**Przewidywane zachowanie**
Co powinno się stać według ciebie

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Naprawione
