### ISSUE TITLE
Moby i zwierzęta nie mogą wchodzić do łódek

### ISSUE THREAD

**Issue by Sfiksowany** [SpaceMC-EU/SpaceMC-Bugi#21]
**Opisz bug**
Tak jak w temacie zwierzęta nie mogą wchodzić do łódek

Opisz dokładnie bug co się dzieje
Zwierzęta nawet stojąc na łódce nie wsiadają do niej co utrudnia rozgrywkę.

Jak go się reprodukuje czyli odtwarza / powtarza
Nie wiem o co chodzi 

Co powinno się stać według ciebie
Zwierzęta powinny wsiadać do łódek ponieważ inaczej nie da się ich przewozić.

**Comment by PuccyDestroyerxXx** [comment]
Nie jest uważane to za bug bardziej optymalizacja serwera wieśniacy nadal mogą wchodzić do łódek
Zamykam.
