### ISSUE TITLE
/warp pvp

### ISSUE THREAD

**Issue by frankakaka** [SpaceMC-EU/SpaceMC-Bugi#26]
**Opisz bug**
jak missne perełke w /warp pvp i przerzuce to tepnie mnie na ściane za

**To Reproduce**
perelką

**Przewidywane zachowanie**
jak sie przerzuci perelką i ona tepnie tam to by powracało gracza tam gdzie był

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Naprawione 1.5 dnia rangi gold możesz komuś dać lub zatrzymać na później
