### ISSUE TITLE
stivoncase i elytra

### ISSUE THREAD

**Issue by frankakaka** [SpaceMC-EU/SpaceMC-Bugi#27]
**Opisz bug**
jak wszedłem zrespiłem się przy stivonie i wypadla elytra

**To Reproduce**
wchodzi na serwer spacemc.eu

**Przewidywane zachowanie**
oddanie mi elytry

**Screenshots**
![image](https://user-images.githubusercontent.com/83536371/116861036-c03bf900-ac02-11eb-9579-436e6337a373.png)

**Comment by frankakaka** [comment]
![image](https://user-images.githubusercontent.com/83536371/116861106-dd70c780-ac02-11eb-91bc-c45c2aaf444f.png)

**Comment by PuccyDestroyerxXx** [comment]
![image](https://user-images.githubusercontent.com/44524396/116861691-d4342a80-ac03-11eb-9fca-2a3f0be9787a.png)

**Comment by PuccyDestroyerxXx** [comment]
Musiałeś wyrzucić elytre nie ma innej opcji musiałeś nacisnąć przycisk Q chyba że masz wirusa na komputerze to bardziej brzmi jak twój problem
