### ISSUE TITLE
naprawienie mobow

### ISSUE THREAD

**Issue by frankakaka** [SpaceMC-EU/SpaceMC-Bugi#28]
**Opisz bug**
przed wymianą silnika na minute w ekspiarce sie respiło z 20 endermanów jak było 10 osb, a teraz w 2, 3 minuty sie respią jak jestem sam na serwerze

**To Reproduce**
Stoi się w ekspiarce

**Przewidywane zachowanie**
większy resp mobów

**Screenshots**
nie da się

**Comment by PuccyDestroyerxXx** [comment]
Nie bug
