### ISSUE TITLE
Shumi_

### ISSUE THREAD

**Issue by Kazz-hash** [SpaceMC-EU/SpaceMC-Bugi#3]
**Opisz bug**
Pigliny umieją latać

**To Reproduce**
Dajesz złoto piglinowi i go podkopujesz i lewituje 

**Przewidywane zachowanie**
Nie powinny latać

**Screenshots**
![2021-04-07_23 00 44](https://user-images.githubusercontent.com/81614959/113984520-7e11d880-984b-11eb-848c-dd31d46c1389.png)

**Comment by PuccyDestroyerxXx** [comment]
Przetestowałem i nie latały to jest prawdopodobnie bug związany z twoim internetem lub coś podobnego nie zaliczam tego
