### ISSUE TITLE
nie działa /xp

### ISSUE THREAD

**Issue by akukwq** [SpaceMC-EU/SpaceMC-Bugi#4]
**Opisz bug**
Opisz dokładnie bug co się dzieje
kiedt pisze /xpb pisze że niemam uprawnień

**To Reproduce**
Jak go się reprodukuje czyli odtwarza / powtarza

**Przewidywane zachowanie**
Co powinno się stać według ciebie
zamienić xp na butelki 

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Zapomniałem po prostu dodać /xpb i pewnie wpisałeś /xp i tak zalicze to jako bug bo warto było przypomnieć o tym
