### ISSUE TITLE
portal na spawnie

### ISSUE THREAD

**Issue by akukwq** [SpaceMC-EU/SpaceMC-Bugi#5]
**Opisz bug**
Opisz dokładnie bug co się dzieje
Na spawnie w drzewie znajduje się portal który miał randomowo teleportować, a gdy do tego portalu się wskoczy teleportacje odrzuca ze względu na to, że gdy masz się teleportować teleportacja zostaje odrzucona przez to, że spadasz.

**To Reproduce**
Jak go się reprodukuje czyli odtwarza / powtarza
Wskakujesz do portalu a reszta dzieje się sama

**Przewidywane zachowanie**
Co powinno się stać według ciebie
teleportować natychmiastowo 
**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Naprawiono z dodaniem nowego plugina handlującego RTP posiadający najszybsze algo do tepania ludzi w losowe miejsca i zmieniono z /tpr na /rtp w skrócie naprawione
