### ISSUE TITLE
curse case

### ISSUE THREAD

**Issue by akukwq** [SpaceMC-EU/SpaceMC-Bugi#6]
**Opisz bug**
Opisz dokładnie bug co się dzieje
w /warp cursecase są item framy, lecz do tych item framów można wkładać itemy tak samo jak niszczyć je.
**To Reproduce**
Jak go się reprodukuje czyli odtwarza / powtarza
wkładasz rzecz do item rame albo niszczysz item frame

**Przewidywane zachowanie**
Co powinno się stać według ciebie
powinno wyskoczyć że nie mogę tego zniszczyć albo, że nie mam uprawnień
**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów
 
P.S
właśnie odkryłem, że item framy można stawiać w każdym miejscu na spawnie

**Comment by PuccyDestroyerxXx** [comment]
To już Boro12 zgłaszał ale dziękuje wciąż za info
