### ISSUE TITLE
./case get

### ISSUE THREAD

**Issue by Ruske123** [SpaceMC-EU/SpaceMC-Bugi#7]
**Opisz bug**
Po wpisaniu komendy /case get stivoncase otrzymujemy zwykłą skrzynię

**To Reproduce**
Wpisać wyżej wymienioną komendę

**Przewidywane zachowanie**
Powinno się otrzymać stivoncase'a (chyba, nie znam się)

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Dobrze pasuje otrzymujesz skrzynie którą trzeba postawić narazie plugin nie obsługuje ikon skrzyniowych
