### ISSUE TITLE
Zmiana wagi skrzyni

### ISSUE THREAD

**Issue by Ruske123** [SpaceMC-EU/SpaceMC-Bugi#8]
**Opisz bug**
Po zmianie wagi /case editweight waga skrzyni pozostaje niezmieniona, pomimo powiadomienia o udanej zmianie 

**To Reproduce**
Wpisać komendę

**Przewidywane zachowanie**
Zmiana wagi skrzyni

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Bug wizualny i tak za bardzo nie było to potrzebne graczom do wiadomości bug wizualny pewnie z powodu tego że obliczony weight jest prekalkulowany i nie za bardzo czytany nie wiem może zostanie naprawione narazie zamykam bo nie warto tego naprawiać gdyż nie wiem dokładnie jak to zrobić 

A ta komenda i tak była stworzona w celu debugu
