### ISSUE TITLE
Znowu case xD

### ISSUE THREAD

**Issue by Ruske123** [SpaceMC-EU/SpaceMC-Bugi#9]
**Opisz bug**
Nie można tworzyć skrzyń testowych, po wpisaniu komendy wyskakuje zły argument nr.3

**To Reproduce**
Spróbować stworzyć nową skrzynię

**Przewidywane zachowanie**
Powinna się stworzyć nową skrzynia

**Screenshots**
Jeśli da się daj dodatkowe informacje w postaci ss'ów

**Comment by PuccyDestroyerxXx** [comment]
Skrzynia posiada zapewnie 0 itemów w sobie i z tego powodu pewnie się jej nie da otworzyć
